# Generated by Django 5.0.3 on 2024-05-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('unique_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('role', models.CharField(default='', max_length=50)),
                ('spell_to_max', models.CharField(default='', max_length=100)),
                ('summoner_spell_1', models.CharField(default='', max_length=100)),
                ('summoner_spell_2', models.CharField(default='', max_length=100)),
                ('rune_main_tree', models.CharField(default='', max_length=100)),
                ('rune_main_keystone', models.CharField(default='', max_length=100)),
                ('rune_main_1', models.CharField(default='', max_length=100)),
                ('rune_main_2', models.CharField(default='', max_length=100)),
                ('rune_main_3', models.CharField(default='', max_length=100)),
                ('rune_secondary_tree', models.CharField(default='', max_length=100)),
                ('rune_secondary_1', models.CharField(default='', max_length=100)),
                ('rune_secondary_2', models.CharField(default='', max_length=100)),
                ('rune_shard_1', models.CharField(default='', max_length=100)),
                ('rune_shard_2', models.CharField(default='', max_length=100)),
                ('rune_shard_3', models.CharField(default='', max_length=100)),
                ('item_1', models.CharField(default='', max_length=100)),
                ('item_2', models.CharField(default='', max_length=100)),
                ('item_3', models.CharField(default='', max_length=100)),
                ('item_4', models.CharField(default='', max_length=100)),
                ('item_5', models.CharField(default='', max_length=100)),
                ('item_6', models.CharField(default='', max_length=100)),
                ('starter_item', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
