# Generated by Django 4.2.4 on 2023-08-31 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lor_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
