# Generated by Django 4.2.4 on 2023-09-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lor_backend', '0003_champion_item_1_champion_item_2_champion_item_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='id',
        ),
        migrations.AddField(
            model_name='champion',
            name='unique_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
