# Generated by Django 5.0.3 on 2024-04-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lor_backend', '0004_remove_champion_id_champion_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='starter_item',
            field=models.CharField(default='', max_length=100),
        ),
    ]
